export const RESPONSES_CONTAINER_XPATH = '//*[@id="root"]/div[1]/div/div/div[2]/div/div[1]/div/div[3]/div/div[1]/div[1]/div';
export const ANONYMOUS_MODE_BUTTON_SELECTOR = 'button[aria-label^="Use o modo anônimo"]';
export const STOP_BUTTON_SELECTOR = 'button[aria-label="Interromper resposta (Esc)"]';
export const LOGIN_MODAL_SELECTOR = '::-p-text(Sign in), ::-p-text(Log in)';
export const VERIFY_URL_INDICATOR = '/auth/verify-request?email=';
export const EMAIL_INPUT_SELECTOR = 'input[type="email"]';
export const COPY_BUTTON_SELECTOR = 'button[aria-label="Copiar"]';
export const VERIFY_BUTTON_SELECTOR = 'button[type="submit"]';
export const CODE_INPUT_SELECTOR = 'input[inputmode="numeric"]';
export const PERPLEXITY_URL = 'https://www.perplexity.ai/';
export const ASK_INPUT_SELECTOR = '#ask-input';
export const NETWORK_IDLE_EVENT = 'networkidle2' as const;
export const CLIPBOARD_WRITE = 'clipboard-write' as const;
export const CLIPBOARD_READ = 'clipboard-read' as const;
export const USER_EMAIL = process.env.EMAIL ?? '';
export const PUPPETEER_ARGS = ['--no-sandbox', '--disable-setuid-sandbox'];
export const GENERATION_TIMEOUT = 60000;
export const ENTER_KEY = 'Enter' as const;
export const VIEWPORT_HEIGHT = 720;
export const VIEWPORT_WIDTH = 1280;
export const CLIPBOARD_DELAY = 500;
export const BUTTON_WAIT = 5000;
export const TYPING_DELAY = 100;
export const CODE_LENGTH = 6;
export const DIV_TAG = 'DIV';