export const RESPONSES_CONTAINER_XPATH = '//*[@id="root"]/div[1]/div/div/div[2]/div/div[1]/div/div[3]/div/div[1]/div[1]/div';
export const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';
export const VIEWPORT_HEIGHT = 1080;
export const VIEWPORT_WIDTH = 1920;
export const PUPPETEER_ARGS = ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--disable-software-rasterizer', '--disable-blink-features=AutomationControlled', '--disable-infobars', '--window-position=0,0', `--window-size=${VIEWPORT_WIDTH},${VIEWPORT_HEIGHT}`, '--ignore-certificate-errors', '--ignore-certificate-errors-spki-list'];
export const ANONYMOUS_MODE_BUTTON_SELECTOR = 'button[aria-label^="Use o modo anônimo"]';
export const STOP_BUTTON_SELECTOR = 'button[aria-label="Interromper resposta (Esc)"]';
export const LOGIN_MODAL_SELECTOR = '::-p-text(Sign in), ::-p-text(Log in)';
export const ACCEPT_LANGUAGE = 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7';
export const VERIFY_URL_INDICATOR = '/auth/verify-request?email=';
export const EMAIL_INPUT_SELECTOR = 'input[type="email"]';
export const COPY_BUTTON_SELECTOR = 'button[aria-label="Copiar"]';
export const VERIFY_BUTTON_SELECTOR = 'button[type="submit"]';
export const CODE_INPUT_SELECTOR = 'input[inputmode="numeric"]';
export const PERPLEXITY_URL = 'https://www.perplexity.ai/';
export const ASK_INPUT_SELECTOR = '#ask-input';
export const NETWORK_IDLE_EVENT = 'networkidle2' as const;
export const CLIPBOARD_WRITE = 'clipboard-write' as const;
export const CLIPBOARD_READ = 'clipboard-read' as const;
export const USER_EMAIL = process.env.EMAIL ?? '';
export const PROTOCOL_TIMEOUT = 180000;
export const GENERATION_TIMEOUT = 60000;
export const ENTER_KEY = 'Enter' as const;
export const CLIPBOARD_DELAY = 500;
export const TYPING_DELAY = 100;
export const BUTTON_WAIT = 5000;
export const CODE_LENGTH = 6;
export const DIV_TAG = 'DIV';